apiVersion: v1
data:
  BACKEND_GRPC_URL: wallet-backend-service-grpc:8448
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: wallet-admin
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: wallet-admin-config
    app.kubernetes.io/version: v1.2.16
    helm.sh/chart: ilf-wallet-admin-2.1.1
  name: wallet-admin-config