apiVersion: v1
kind: Service
metadata:
  annotations: null
  labels:
    app.kubernetes.io/instance: wallet-admin
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: wallet-admin-service
    app.kubernetes.io/version: v1.2.16
    helm.sh/chart: ilf-wallet-admin-2.1.1
  name: wallet-admin-service
spec:
  ports:
  - name: http
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app.kubernetes.io/instance: wallet-admin
    app.kubernetes.io/name: wallet-admin-server
  type: ClusterIP