name: Build and Push Chart Validator

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'chartvalidator/**'
  pull_request:
    branches:
      - main
    paths:
      - 'chartvalidator/**'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: interledger/builders/chartvalidator

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      packages: write
      id-token: write
      attestations: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        # Only login if we're going to push (matches the push condition)
        if: (github.ref == 'refs/heads/main') && (github.event_name == 'push' || github.event_name == 'workflow_dispatch')
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest
          labels: |
            org.opencontainers.image.description=Chart validator tool for Interledger
            org.opencontainers.image.vendor=Interledger Foundation

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./chartvalidator
          # Only push on main branch (PR merge), otherwise just build
          push: ${{ (github.ref == 'refs/heads/main') && (github.event_name == 'push' || github.event_name == 'workflow_dispatch') }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
